services:
  backend:
    build:
      context: ../backend.Dockerfile
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8888:8888"
    volumes:
      - /home/informania/Code/informania/backend:/opt/backend
      - /home/informania/Code/informania/backend-source:/opt/backend-source
    working_dir: /opt/backend
    command: ["jupyter", "notebook", "--notebook-dir=/opt/backend/notebooks", "--ip=0.0.0.0", "--port=8888", "--allow-root", "--NotebookApp.token="]
    restart: always
